DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS target_word;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS user_guess;

CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE target_word (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word TEXT NOT NULL
);

CREATE TABLE user_guess (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    guess TEXT NOT NULL,
    similarity_score REAL NOT NULL,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);

